title: "akshit"
author: "viciousaegis"
description: "throughout heaven and earth, i alone am the honored one"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: home}
  - {file: "projects.md", title: projects}
  - {file: "blog.html", title: blog}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Twitter, icon: twitter, url: "https://twitter.com/akshitwt"}
  - {title: Github, icon: github, url: "https://github.com/viciousAegis"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/akshit-sinha-b2b138222/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
